version: "3.8"
services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=herosquad
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 0:5432
    volumes:
      - db:/var/lib/postgres

  app:
    depends_on:
     - postgresdb
    build: .
    ports:
      - 0:4567
volumes:
  db :